MtMoon_1F_Text_UseDPad::
# 1 "data/maps/MtMoon_1F/text.pory"
	.string "Use {DPAD_ANY} to slide a block in the chosen\n"
	.string "direction into the empty space.\p"
	.string "Bring the number 1\n"
	.string "to the top left corner.$"

MtMoon_1F_Text_CantMoveBorderedBlocks::
# 8 "data/maps/MtMoon_1F/text.pory"
	.string "Blocks with a dashed outline\n"
	.string "can't slide.\p"
	.string "Complete the top row with the\n"
	.string "sequence of numbers from 1 to 4.$"

MtMoon_1F_Text_Complete3x3::
# 15 "data/maps/MtMoon_1F/text.pory"
	.string "Complete the whole puzzle with the\n"
	.string "sequence of numbers from 1 to 15.$"

MtMoon_1F_Text_CanRotateRoundedBlocks::
# 20 "data/maps/MtMoon_1F/text.pory"
	.string "Use {SELECT_BUTTON} to switch between\n"
	.string "Arrows Mode and Cursor Mode.\p"
	.string "While in Cursor Mode, use {DPAD_ANY} to move\n"
	.string "the hand cursor across blocks.\l"
	.string "Press {A_BUTTON} to slide the block under\l"
	.string "the cursor into the empty space,\l"
	.string "or press {L_BUTTON} or {R_BUTTON} to rotate it\l"
	.string "counterclockwise or clockwise.\p"
	.string "Only blocks with rounded corners can\n"
	.string "be rotated.$"

MtMoon_1F_Text_ImpossiblePuzzles::
# 33 "data/maps/MtMoon_1F/text.pory"
	.string "If a puzzle only needs to swap\n"
	.string "two blocks to be solved, it is\l"
	.string "unsolvable, but this one is not.$"
