MtMoon_1F_Text_UseDPad::
# 1 "data/maps/MtMoon_1F/text.pory"
	.string "Use {DPAD_ANY} to slide a block in the chosen\n"
	.string "direction into the empty space.\p"
	.string "Bring the number 1\n"
	.string "to the top left corner.$"

MtMoon_1F_Text_CantMoveBorderedBlocks::
# 8 "data/maps/MtMoon_1F/text.pory"
	.string "Blocks with a dashed outline\n"
	.string "can't slide.\p"
	.string "Complete the top row with the sequence\n"
	.string "of numbers from 1 to 4.$"

MtMoon_1F_Text_Complete3x3::
# 15 "data/maps/MtMoon_1F/text.pory"
	.string "Complete the whole puzzle with\n"
	.string "the sequence of numbers from 1 to 15.$"
