SevenIsland_TrainerTower_Text_PuzzlePalace::
# 1 "data/maps/SevenIsland_TrainerTower/text.pory"
	.string "Welcome to BRAINING PALACE!$"

SevenIsland_TrainerTower_Text_WelcomeToBrainingIsland::
# 5 "data/maps/SevenIsland_TrainerTower/text.pory"
	.string "Welcome to BRAINING ISLAND!\n"
	.string "This is a place in the middle\l"
	.string "of the ocean, with nothing to do\l"
	.string "but take on the challenge\l"
	.string "of BRAINING PALACE.\p"
	.string "The reward for beating it is…\n"
	.string "Nothing! Nothing but glory!$"

SevenIsland_TrainerTower_Text_HoOh::
# 15 "data/maps/SevenIsland_TrainerTower/text.pory"
	.string "HO-OH, the Pokémon you befriended\n"
	.string "a long time ago, shall come along.$"

SevenIsland_TrainerTower_DoYourBest::
# 20 "data/maps/SevenIsland_TrainerTower/text.pory"
	.string "Do your best!$"
