VictoryRoad_1F_Text_FloorName::
# 1 "data/maps/VictoryRoad_1F/text.pory"
	.string "Floor VI\n"
	.string "-- Master of all trades --$"

VictoryRoad_1F_Text_NothingHappened::
# 6 "data/maps/VictoryRoad_1F/text.pory"
	.string "Nothing happened.$"

VictoryRoad_1F_Text_ImpossibleNothingHappened::
# 10 "data/maps/VictoryRoad_1F/text.pory"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible.\n"
	.string "Nothing happened.$"

VictoryRoad_1F_Text_MagicSquare::
# 15 "data/maps/VictoryRoad_1F/text.pory"
	.string "This puzzle is called\n"
	.string "a magic square.\p"
	.string "Arrange the tiles so that all rows,\n"
	.string "all columns and both diagonals\l"
	.string "add up to the same number.\p"
	.string "The empty space is equal to 1.$"

VictoryRoad_1F_Text_Credits::
# 24 "data/maps/VictoryRoad_1F/text.pory"
	.string "POKéMON - Let it slide!\n"
	.string "CREDITS\p"
	.string "AUTHOR - Nicolavs\n"
	.string "BASE GAME - GAME FREAK\p"
	.string "GRAPHICS\n"
	.string "GAME FREAK\l"
	.string "Nicolavs\l"
	.string "Protagonist's sprites: hyo\l"
	.string "Eusine's sprites: Project Palladium\p"
	.string "MUSIC\n"
	.string "GAME FREAK\p"
	.string "Title theme: Unknown artist\l"
	.string "Overworld theme: Bulgasali\l"
	.string "Battle theme: Daniel Lawrence\l"
	.string "Puzzles theme 1: Unknown artist\l"
	.string "Puzzles theme 2: (MoldyPond)\l"
	.string "Puzzles theme 3: Unknown artist\l"
	.string "Puzzles theme 4: Unknown artist\l"
	.string "Puzzles theme 5: Unknown artist\l"
	.string "Final puzzle theme: Unknown artist\l"
	.string "Final battle theme: Xenu\p"
	.string "Project subitted to\n"
	.string "{FONT_SMALL}3rd Team Aqua's ROM-Hacking Competition.$"
