VictoryRoad_1F_Text_FloorName::
# 1 "data/maps/VictoryRoad_1F/text.pory"
	.string "Floor VI\n"
	.string "-- Master of all trades --$"

VictoryRoad_1F_Text_NothingHappened::
# 6 "data/maps/VictoryRoad_1F/text.pory"
	.string "Nothing happened.$"

VictoryRoad_1F_Text_ImpossibleNothingHappened::
# 10 "data/maps/VictoryRoad_1F/text.pory"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible.\n"
	.string "Nothing happened.$"

VictoryRoad_1F_Text_MagicSquare::
# 15 "data/maps/VictoryRoad_1F/text.pory"
	.string "This puzzle is called\n"
	.string "a magic square.\p"
	.string "Arrange the tiles so that all rows,\n"
	.string "all columns and both diagonals\l"
	.string "add up to the same number.\p"
	.string "The empty space is equal to 1.$"

VictoryRoad_1F_Text_RockerIntro::
# 24 "data/maps/VictoryRoad_1F/text.pory"
	.string "You won't go any further\n"
	.string "without a battle!$"

VictoryRoad_1F_Text_RockerDefeated::
# 29 "data/maps/VictoryRoad_1F/text.pory"
	.string "I failed to stop you.\n"
	.string "You deserve to keep going.$"

VictoryRoad_1F_Text_ImStuck::
# 34 "data/maps/VictoryRoad_1F/text.pory"
	.string "I think I'm stuck here, am I not?$"

VictoryRoad_1F_Text_ThisIsTooDifficult::
# 38 "data/maps/VictoryRoad_1F/text.pory"
	.string "This is too difficult!\n"
	.string "I'm not cut for these puzzles!$"

VictoryRoad_1F_Text_ImLookingForMetragross::
# 43 "data/maps/VictoryRoad_1F/text.pory"
	.string "I'm looking for METAGROSS,\n"
	.string "but I don't know how rare it is.\p"
	.string "I've been searching for half an hour!$"
