VictoryRoad_1F_Text_FloorName::
# 1 "data/maps/VictoryRoad_1F/text.pory"
	.string "Floor VI\n"
	.string "-- Master of all trades --$"

VictoryRoad_1F_Text_NothingHappened::
# 6 "data/maps/VictoryRoad_1F/text.pory"
	.string "Nothing happened.$"

VictoryRoad_1F_Text_ImpossibleNothingHappened::
# 10 "data/maps/VictoryRoad_1F/text.pory"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible.\n"
	.string "Nothing happened.$"

VictoryRoad_1F_Text_MagicSquare::
# 15 "data/maps/VictoryRoad_1F/text.pory"
	.string "This puzzle is called\n"
	.string "a magic square.\p"
	.string "Arrange the tiles so that all rows,\n"
	.string "all columns and both diagonals\l"
	.string "add up to the same number.\p"
	.string "The empty space is equal to 1.$"
