#ifndef GUARD_CONSTANTS_SLIDING_BLOCKS_H
#define GUARD_CONSTANTS_SLIDING_BLOCKS_H

#define SLIDING_LAYOUT_TEST_HO_OH   0
#define SLIDING_LAYOUT_VOLTORB      1
#define SLIDING_LAYOUT_ELECTRODE    2
#define SLIDING_LAYOUT_NUMBERS_1    3
#define SLIDING_LAYOUT_NUMBERS_1234 4
#define SLIDING_LAYOUT_NUMBERS_3X3  5

#endif
