MtMoon_B1F_Text_FloorName::
# 1 "data/maps/MtMoon_B1F/text.pory"
	.string "Floor I\n"
	.string "-- The whole picture --$"

MtMoon_B1F_Text_YoungsterIntro::
# 6 "data/maps/MtMoon_B1F/text.pory"
	.string "Battle! Now!$"

MtMoon_B1F_Text_YoungsterDefeated::
# 10 "data/maps/MtMoon_B1F/text.pory"
	.string "Battle… lost.$"

MtMoon_B1F_Text_WhatGoOn::
# 14 "data/maps/MtMoon_B1F/text.pory"
	.string "What?! Go on!$"
