MtMoon_B2F_Text_FloorName::
# 1 "data/maps/MtMoon_B2F/text.pory"
	.string "Floor II\n"
	.string "-- VOLTORB Flip --$"

MtMoon_B2F_Text_MakeElectrode::
# 6 "data/maps/MtMoon_B2F/text.pory"
	.string "Make ELECTRODE.$"

MtMoon_B2F_Text_MakeElectrodeAgain::
# 10 "data/maps/MtMoon_B2F/text.pory"
	.string "Make ELECTRODE again.$"

MtMoon_B2F_Text_CooltrainerIntro::
# 14 "data/maps/MtMoon_B2F/text.pory"
	.string "Challenger found! Now, let's battle!$"

MtMoon_B2F_Text_CooltrainerDefeated::
# 18 "data/maps/MtMoon_B2F/text.pory"
	.string "Cool!$"

MtMoon_B2F_Text_YoureCoolEnough::
# 22 "data/maps/MtMoon_B2F/text.pory"
	.string "You're cool enough.\n"
	.string "Do your best!$"

MtMoon_B2F_Text_BlackBeltIntro::
# 27 "data/maps/MtMoon_B2F/text.pory"
	.string "Are you enjoying yourself so far?\n"
	.string "Let's spice things up!$"

MtMoon_B2F_Text_BlackBeltDefeated::
# 32 "data/maps/MtMoon_B2F/text.pory"
	.string "You're on fire!$"

MtMoon_B2F_Text_ThingsWillEscalateQuickly::
# 36 "data/maps/MtMoon_B2F/text.pory"
	.string "Things will escalate quickly.\n"
	.string "This place gives headaches!$"
