DiglettsCave_NorthEntrance_Text_FloorName::
# 1 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "Floor III\n"
	.string "-- Obstacle course --$"

DiglettsCave_NorthEntrance_Text_HowAboutABattle::
# 6 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "Hey, challenger!\n"
	.string "How about a battle?\l"
	.string "If you win, I'll give you an item.$"

DiglettsCave_NorthEntrance_Text_LetsGo::
# 12 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "Let's go!$"

DiglettsCave_NorthEntrance_Text_ComeBackIfYouCangeYourMind::
# 16 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "Nevermind then.\n"
	.string "Come back if you change your mind.$"

DiglettsCave_NorthEntrance_Text_YouWinThisOne::
# 21 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "You win this one!$"

DiglettsCave_NorthEntrance_Text_TakeMasterBall::
# 25 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "Good job!\n"
	.string "I see you only have a few POKéMON\l"
	.string "with you.\l"
	.string "Here, take this!$"

DiglettsCave_NorthEntrance_Text_TakeSitrusBerry::
# 32 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "Good job! Here's the item I promised.$"

DiglettsCave_NorthEntrance_Text_IllBattleYouAgain::
# 36 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "I'll battle against you\n"
	.string "anytime you want.$"

DiglettsCave_NorthEntrance_Text_IllHaveToSolveItMyself::
# 41 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "Yeah, you solved it, but I can't\n"
	.string "pass: it'll close again for me\l"
	.string "until I've solved it myself.$"

DiglettsCave_NorthEntrance_Text_ThisOneIsHard::
# 47 "data/maps/DiglettsCave_NorthEntrance/text.pory"
	.string "This one is stumping me!\n"
	.string "The previous puzzles weren't as hard!$"
