DiglettsCave_SouthEntrance_Text_FloorName::
# 1 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "-- The lost woods --$"

DiglettsCave_SouthEntrance_Text_1::
# 5 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "I$"

DiglettsCave_SouthEntrance_Text_2::
# 9 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "II$"

DiglettsCave_SouthEntrance_Text_3::
# 13 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "III$"

DiglettsCave_SouthEntrance_Text_4::
# 17 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "IV$"

DiglettsCave_SouthEntrance_Text_5::
# 21 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "V$"

DiglettsCave_SouthEntrance_Text_6::
# 25 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "VI$"

DiglettsCave_SouthEntrance_Text_Impossible1::
# 29 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "I\n"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible$"

DiglettsCave_SouthEntrance_Text_Impossible2::
# 34 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "II\n"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible$"

DiglettsCave_SouthEntrance_Text_Impossible3::
# 39 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "III\n"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible$"

DiglettsCave_SouthEntrance_Text_Impossible4::
# 44 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "IV\n"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible$"

DiglettsCave_SouthEntrance_Text_Impossible5::
# 49 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "V\n"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible$"

DiglettsCave_SouthEntrance_Text_Impossible6::
# 54 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "VI\n"
	.string "{FONT_SMALL}This puzzle is supposed to be impossible$"

DiglettsCave_SouthEntrance_Text_KeepGoingLeft::
# 59 "data/maps/DiglettsCave_SouthEntrance/text.pory"
	.string "I'm stuck, I can't figure out how to\n"
	.string "traverse this floor.\p"
	.string "If you're lost, keep going left and\n"
	.string "you'll come back here eventually.\l"
	.string "That much, I was able to find out.$"
